<a href="https://colab.research.google.com/github/flatplanet/Data_Analysis_With_Python_Course/blob/main/Numpy_3_Universal_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Numeric Python - Universal Functions (ufuncs)

In [ ]:
np1 = np.array([-3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8,9])
print(np1)

[-3 -2 -1  0  1  2  3  4  5  6  7  8  9]


In [ ]:
# Square Root
print(np.sqrt(np1))

[       nan        nan        nan 0.         1.         1.41421356
 1.73205081 2.         2.23606798 2.44948974 2.64575131 2.82842712
 3.        ]


/tmp/ipython-input-1725249946.py:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(np1))


In [ ]:
# Absolute Value
print(np.absolute(np1))

[3 2 1 0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Exponential
print(np.exp(np1))

[4.97870684e-02 1.35335283e-01 3.67879441e-01 1.00000000e+00
 2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]


In [ ]:
# Min/Max
print(np1)
# Min
#np.min(np1)
print(np.max(np1))

[-3 -2 -1  0  1  2  3  4  5  6  7  8  9]
9


In [ ]:
# Positive/Negative -1 = negative 1 = positive
print(np.sign(np1))

[-1 -1 -1  0  1  1  1  1  1  1  1  1  1]


In [ ]:
# Trig Functions - Sin, Cos, Log
#print(np.sin(np1))
#print(np.cos(np1))
print(np.log(np1))

[       nan        nan        nan       -inf 0.         0.69314718
 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015 2.07944154
 2.19722458]


/tmp/ipython-input-2935338023.py:4: RuntimeWarning: divide by zero encountered in log
  print(np.log(np1))
/tmp/ipython-input-2935338023.py:4: RuntimeWarning: invalid value encountered in log
  print(np.log(np1))


In [ ]:
# Master List
# https://numpy.org/doc/stable/reference/ufuncs.html