<a href="https://colab.research.google.com/github/flatplanet/Data_Analysis_With_Python_Course/blob/main/Numpy_2_Python_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Numeric Python - Slices

In [ ]:
# Slicing NumPy Arrays - Return 2,3,4,5| Slice 1:5 returns 1 up till 5 but not including 5
np1 = np.array([1,2,3,4,5,6,7,8,9])
print(np1[1:5])  # 5 is up till but not including 5
np2 = np1[1:5]
print(np2)

[2 3 4 5]
[2 3 4 5]


In [ ]:
# Return from something till end or array
print(np1[3:])  # :nothing means till the end

[4 5 6 7 8 9]


In [ ]:
# Return negative slices, from the end backwards
print(np1[-3:-1])  # -1 is up till but not including -1

[7 8]


In [ ]:
# Slices with Steps
print(np1[1:5])
print(np1[1:5:3])

[2 3 4 5]
[2 5]


In [ ]:
# Slices whole thing in steps
print(np1)
print(np1[::2])


[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [ ]:
# Slice a 2-d array
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# Pull out a single item '8'
print(np2[1,2])

8


In [ ]:
# Pull slices from 1 of 2-dimension
print(np2[0:1,1:3])  # Row, Item

[[2 3]]


In [ ]:
# Pull slices from both dimensions (2,3 and 7,8)
print(np2[0:2,1:3])  # row item

[[2 3]
 [7 8]]
