<a href="https://colab.research.google.com/github/flatplanet/Data_Analysis_With_Python_Course/blob/main/Pandas_2_Manual_DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas - Manual DataFrames

In [1]:
# Import Pandas
import pandas as pd
import numpy as np
from numpy.random import rand

In [2]:
# Create a Random Data
my_data = rand(4,3) # rows/columns
print(my_data)

[[0.57708466 0.48677537 0.35465777]
 [0.68711767 0.45072448 0.89049525]
 [0.0763666  0.44014508 0.22447488]
 [0.68569712 0.4378124  0.76998933]]


In [3]:
# Create headers
my_rows = ["A", "B", "C", "D"]
my_cols = ["Monday", "Tuesday", "Friday"]

In [4]:
# Create our DataFrame!!
my_df = pd.DataFrame(my_data, my_rows, my_cols)

In [5]:
# print
print(my_df)

     Monday   Tuesday    Friday
A  0.577085  0.486775  0.354658
B  0.687118  0.450724  0.890495
C  0.076367  0.440145  0.224475
D  0.685697  0.437812  0.769989


In [6]:
# print with formatting
my_df

Monday   Tuesday    Friday
A  0.577085  0.486775  0.354658
B  0.687118  0.450724  0.890495
C  0.076367  0.440145  0.224475
D  0.685697  0.437812  0.769989