<a href="https://colab.research.google.com/github/flatplanet/Data_Analysis_With_Python_Course/blob/main/Python_Data_Analysis_Course_Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numeric Python

In [20]:
# Python list
my_list = [1,2,3,4,5, "John", True]
my_list2 = [6,7,8, my_list]

In [26]:
# Import Numpy
import numpy as np

In [25]:
# Create a numpy array
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)
print(np1[2])

[0 1 2 3 4 5 6 7 8 9]
2


In [40]:
# Shape - shows the number of elements in the array like the python len function
print(np1.shape)

(10,)


In [43]:
# Arange
np2 = np.arange(10)
print(np2)

[0 1 2 3 4 5 6 7 8 9]


In [48]:
# Step
np3 = np.arange(0,10,2)
print(np3)

[0 2 4 6 8]


In [49]:
# Zeros
np4 = np.zeros(10)
print(np4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [51]:
# Multi-Dimensional Arrays with Zeros
np5 = np.zeros((5,10))
print(np5)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [54]:
# Full
np6 = np.full((10), "Bob")
print(np6)

['Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob']


In [56]:
# Multi-Dimensional Array with Full
np7 = np.full((2, 10), "Bob")
print(np7)

[['Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob']
 ['Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob']]


In [62]:
# Convert Python List to Numpy Array
# my_list
my_list = [0,1,2,3,4,5]
np8 = np.array(my_list)
print(np8)
print(my_list)

[0 1 2 3 4 5]
[0, 1, 2, 3, 4, 5]
